### PR TITLE
refactor: Enable repr for all models

### PR DESCRIPTION
**Pull request by sillyElvy**
## About

This pull request enables the repr in the define defaults. 

## Checklist

- [ ] I've ran `pre-commit` to format and lint the change(s) made.
- [ ] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by sillyElvy** [comment]
Users said they want this in #polls

**Comment by Toricane** [comment]
Does this enable the repr of all attributes? It looks like some are disabled

**Comment by sillyElvy** [comment]
> Does this enable the repr of all attributes? It looks like some are disabled

After some complaints from catalyst I disabled a few but mostly all are covered

**Review by Toricane — APPROVED** [review]
LGTM!

**Pull request merged**
