### PR TITLE
fix button example

### PR DESCRIPTION
**Pull request by Yurab0b**
button => button1

## About

This pull request is about (X), which does (Y).

## Checklist

- [ ] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [x] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by Damego** [comment]
1. Refer to unstable branch
2. Use conventional commits

**Comment by V3ntus** [comment]
I'm not sure what the purpose of this PR is for. Is it a typo? Can you please alter the description accordingly?

This change does not fix anything, in fact, I believe it is misleading and results in an error

**Comment by Damego** [comment]
Yeah its typo

**Comment by FayeDel** [comment]
I'm closing this PR because the PR itself isn't clear of what it should fix, documentation wise this works the way it currently is, and as they said above, just changing this line will result in an error.

If you think this is false, then I'd suggest giving a little more context to the PR and the issue in question so this PR may be reopened. ^^

**Pull request closed without merging**
