### PR TITLE
refactor: split `_dispatch_event` in two methods

### PR DESCRIPTION
**Pull request by Damego**
## About

This pull request splits ``_dispatch_event`` in two other methods.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by Damego** [comment]
Can I include #1004 into this pr?

**Comment by Damego** [comment]
Resolved merge conflict lol. Why it shows changes which already in unstable?

**Comment by Damego** [comment]
oh damn... rebase in third time

**Comment by sillyElvy** [comment]
> oh damn... rebase in third time

Wait until #1022

**Comment by Damego** [comment]
okay

**Comment by Damego** [comment]
Will mark as draft

**Comment by Damego** [comment]
*I hate this pr*

**Comment by sillyElvy** [comment]
> *I hate this pr*

Perfect

**Comment by Damego** [comment]
Its fine now

**Comment by Damego** [comment]
I will reopen this fucking pr

**Comment by Damego** [comment]
fine

**Comment by Catalyst4222** [comment]
Can you resolve conflicts and re-test?

**Comment by Damego** [comment]
> Can you resolve conflicts and re-test?

Resolved and it works

**Comment by Damego** [comment]
image
Merge it pls. Every new rebase takes more time than previous

**Comment by sillyElvy** [comment]
> image Merge it pls. Every new rebase takes more time than previous

I find it satisfying for how long this PR is already opened without being merged and how it just gets worse and worse xD

**Review by sillyElvy — COMMENTED** [review]
Has this been tested with EVERY event and type of command as well as every type of select, different amounts of select menus, etc etc?

**Comment by Damego** [comment]
This pr does not changes code or logic of dispatching. Im just moved code in function. I know its impossible to review this pr and better just look at my branch

**Comment by Damego** [comment]
> > image Merge it pls. Every new rebase takes more time than previous
> 
> I find it satisfying for how long this PR is already opened without being merged and how it just gets worse and worse xD

This pr contain absolutely same code we have on unstable branch soooo do you mean our code gets worse and worse then lol?

**Comment by sillyElvy** [comment]
> > > image Merge it pls. Every new rebase takes more time than previous
> > 
> > I find it satisfying for how long this PR is already opened without being merged and how it just gets worse and worse xD
> 
> This pr contain absolutely same code we have on unstable branch soooo do you mean our code gets worse and worse then lol?

Fine but has it been tested enough to ensure that you did everything correctly? So we know that you did not indent something wrong etc

**Comment by Damego** [comment]
I tested it right now and yes, it works fineee (as expected).
`_dispatch_event` properly calls methods to dispatch interactions and discord events.

**Comment by Damego** [comment]
Review it here https://github.com/Damego/library/blob/ref-split-dispatch/interactions/api/gateway/client.py#L362

**Comment by sillyElvy** [comment]
looks like it needs another rebase (sorry)

**Review by sillyElvy — APPROVED** [review]

**Pull request merged**
