### PR TITLE
refactor!: add ``event`` to ``raw_socket_create`` dispatch

### PR DESCRIPTION
**Pull request by Damego**
## About

This pull request is about (X), which does (Y).

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [x] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Review by Catalyst4222 — CHANGES_REQUESTED** [review]
There are two other places that will need changed, `async def __raw_socket_create` in Client and the event description in `events.rst`

**Comment by Damego** [comment]
> There are two other places that will need changed, `async def __raw_socket_create` in Client and the event description in `events.rst`

oh ok. Thanks. Will do

**Review by Catalyst4222 — APPROVED** [review]

**Comment by Toricane** [comment]
Please resolve merge conflicts

**Comment by Damego** [comment]
Done

**Comment by sillyElvy** [comment]
> Done



Oh dear

**Review by Toricane — APPROVED** [review]
lol this is old, LGTM!

**Pull request merged**
