### PR TITLE
refactor!: Replace the Color class with an enum

### PR DESCRIPTION
**Pull request by Nanrech**
## About

This pull request replaces the `Color` class with an enumerator.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [x] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Review by Damego — CHANGES_REQUESTED** [review]
Keep the class docsting

**Comment by Nanrech** [comment]
Added docstring back

**Review by Damego — APPROVED** [review]

**Comment by mAxYoLo01** [comment]
Any possibility to add all basic colors? Not sure of the usefulness but while we're at it...

**Review by sillyElvy — CHANGES_REQUESTED** [review]
Giving this an X until 4.4 so it doesn't get accidentally merged

**Comment by Damego** [comment]
> Any possibility to add all basic colors? Not sure of the usefulness but while we're at it...

Wdym by basic color?

**Comment by AstreaTSS** [comment]
Perhaps they mean the default role colors?

**Comment by Damego** [comment]
Discord changed green color to bit darker. Can you find new color and replace it?

**Review by sillyElvy — CHANGES_REQUESTED** [review]
Please add information in the migration.rst of the docs about this change (nice sentence structure, I know) and give the section the `4.3.4 -> 4.4.0` title

**Review by sillyElvy — APPROVED** [review]
LGTM!

**Pull request merged**
