### PR TITLE
feat: Implement ``AllowedMentions`` object

### PR DESCRIPTION
**Pull request by Damego**
## About

This pull request adds ``AllowedMentions`` and ``AllowedMentionTypes`` objects to work with ``allowed_mentions``

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [x] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Review by sillyElvy — CHANGES_REQUESTED** [review]
I don't want this to be breaking, so please add an `_._json if isinstance(_, Class) else _` condition to where allowed mentions is used

**Comment by Damego** [comment]
> I don't want this to be breaking, so please add an `_._json if isinstance(_, Class) else _` condition to where allowed mentions is used

Okay. Will do. What about typehinting?
1. Keep current.
2. `Optional[Union[AllowedMentions, Dict[str, list]]]`
3. `Optional[Union[AllowedMentions, Dict[str, List[Union[str, int]]]]]`
4. `Optional[Union[AllowedMentions, dict]]`

**Comment by sillyElvy** [comment]
> 
> 
> > I don't want this to be breaking, so please add an `_._json if isinstance(_, Class) else _` condition to where allowed mentions is used
> 
> Okay. Will do. What about typehinting?
> 1. Keep current.
> 2. `Optional[Union[AllowedMentions, Dict[str, list]]]`
> 3. `Optional[Union[AllowedMentions, Dict[str, List[Union[str, int]]]]]`
> 4. `Optional[Union[AllowedMentions, dict]]`

Late response, sorry, 4 is fine

**Comment by Damego** [comment]
Done

**Review by sillyElvy — APPROVED** [review]

**Pull request merged**
