### PR TITLE
5.9.2

### PR DESCRIPTION
**Pull request by silasary**
Another hotfix 🙃 

See #1523

### CODE REVIEW

**Review by AstreaTSS — APPROVED** [review]
python is a circus and im its clown

**Review by LawMixer — APPROVED** [review]
I've reviewed it and it worked.

**Comment by LordOfPolls** [comment]
what

**Comment by LawMixer** [comment]
hello mr

**Comment by AstreaTSS** [comment]
> what

I heard you like bug fixes, so I bug fixed a bug fix.

**Review by i0bs — APPROVED** [review]

**Pull request merged**
