### PR TITLE
feat(guild, channel): implement new helper methods

### LINKED ISSUE #599: [REQUEST] implement channel invite and channel.get classmethod
^

### PR DESCRIPTION
**Pull request by sillyElvy**
## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [x] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent): resolves #599 
- [ ] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by sillyElvy** [comment]
keeping this as draft until other PRs of me are merged since they're all from the same base branch bruh

**Review by i0bs — COMMENTED** [review]
Do we need the `get` classmethods if we're eventually going for a dynamic solution in the client?

**Comment by sillyElvy** [comment]
Well, we don't "need" them but I figured it would be nice if they existed atleast until that method

**Comment by i0bs** [comment]
My feelings on the existence of `get` being here is similar to #470 in which we want a more dynamic solution to it without having to hardcode it per data model, as well as it'll be done when it's addressed.

**Comment by sillyElvy** [comment]
The `get` methods are removed; merge conflicts corrected

**Review by i0bs — APPROVED** [review]

**Pull request merged**
