### PR TITLE
add support for string custom_id in component callback

### PR DESCRIPTION
**Pull request by Toricane**
## About this Pull Request

This pull request adds support for string custom_id in component callbacks
Does not add anything new, just modifies a couple of lines to allow strings to work
Tested and it works

## Checklist

- [x] I've run the `pre_push.py` script to format and lint the change(s) made.
- [x] I've checked to make sure this pull request runs on Python `3.6.X`.
- [ ] This fixes/solves something from the project's [Issues](https://github.com/goverfl0w/discord-interactions/issues).
    - Issue (if referenceable):
- [ ] This adds something new.
    - [ ] This is not a code change.
    - [ ] (If required) Relevant documentation has been updated/added.
    - [ ] There is/are (a) breaking change(s).

### CODE REVIEW

**Review by V3ntus — APPROVED** [review]
LGTM

**Comment by i0bs** [comment]
Please retarget this to the `unstable` branch. Making pull requests directly to `stable` currently goes against our workflow for unstable/stable design.

**Comment by Toricane** [comment]
noooo i messed it up

**Comment by Toricane** [comment]
I'll make a new PR with the code in the `unstable` branch instead

**Pull request closed without merging**
