### PR TITLE
docs: Update Issues to new URL

### PR DESCRIPTION
**Pull request by mAxYoLo01**
## About

Title

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Review by sillyElvy — CHANGES_REQUESTED** [review]
Am I stupid? I thought I just updated the whole template

**Comment by mAxYoLo01** [comment]
> Am I stupid? I thought I just updated the whole template

Lmao, I actually thought too of seeing some PR like that but maybe I'm too blind to see it??

**Comment by sillyElvy** [comment]
I'm not stupid, your base branch is outdated. The issue link has been removed

**Comment by sillyElvy** [comment]
> > Am I stupid? I thought I just updated the whole template
> 
> Lmao, I actually thought too of seeing some PR like that but maybe I'm too blind to see it??

Check unstable branch code

**Comment by mAxYoLo01** [comment]
oh it's on unstable, that's why... I looked at `documentation`, my bad.

**Pull request closed without merging**
