### PR TITLE
feat: Implement barebones support for Select Menus in Modals.

### PR DESCRIPTION
**Pull request by FayeDel**
## About

This pull request adds compatibility with Select Menus in Modals.

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [X] I've made this pull request for/as: (check all that apply)
  - [X] Documentation
  - [ ] Breaking change
  - [X] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by i0bs** [comment]
Selects in modals has silently been pushed to prod

**Review by i0bs — COMMENTED** [review]
Do we need to update any modal docs and/or typings for it?

**Comment by FayeDel** [comment]
You sure it's been pushed to prod?
I ran it with a testbot and I can't reproduce it

**Comment by Damego** [comment]
same

**Comment by i0bs** [comment]
💀 I ran it with digiorno in a separate, I didn't realize the bot was gated

**Comment by FayeDel** [comment]
gj

**Comment by i0bs** [comment]
Listen life is hard sometimes

**Comment by i0bs** [comment]
I propose for us to close this draft and target changes to `5.x` instead

**Comment by FayeDel** [comment]
Closing to later reopen (or redo PR) for version `5.x`.

**Pull request closed without merging**
