### PR TITLE
feat: implement `client.get()` helper method and improved caching

### PR DESCRIPTION
**Pull request by Toricane**
## About

This pull request is about implementing a helper method `client.get()`, which lets users easily get models from it.
The models that can be outputted are instances of `Channel`, `Guild`, `Member`, `Message`, and `User`.
It also implements `fetch()` classmethods for the aforementioned classes, which the `client.get()` utilizes for dynamic model creation.

The way it works is it will first try to get the model from the cache. If that is not possible, then it will fetch directly from Discord's API.
There is an optional parameter called `cache` which you can set to `False` if you do not want to get from the cache.
A reason that I could think of for why you don't want it from the cache is if the information in the cached model is outdated.

This pull request also improves the caching in all the API model files and in http.py.

I don't think this is a breaking change, shouldn't break any code

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by Toricane** [comment]
Example usage:
```py
@bot.command(
    name="showcase", description="Shows the gets and fetches", scope=874781880489222154
)
async def _get(ctx):
    channel = await bot.get(
        interactions.Channel,
        channel_id=ctx.channel_id,
    )
    guild = await bot.get(
        interactions.Guild,
        guild_id=ctx.guild_id,
    )
    member = await bot.get(
        interactions.Member,
        guild_id=ctx.guild_id,
        member_id=ctx.author.user.id,
    )
    message = await bot.get(
        interactions.Message,
        channel_id=874781880489222154,
        message_id=937146901021741106,
    )
    user = await bot.get(
        interactions.User,
        user_id=ctx.author.user.id,
    )
    await ctx.send(
        f"""
Channel: {channel}
Guild: {guild}
Member: {member}
Message: {message}
User: {user}
"""
    )
```

**Comment by Toricane** [comment]
I have an idea, please don't merge it yet.
The idea is to add to cache or update it at the end of each of the class methods.
Should I keep the caching done by the helper methods in the http client for the corresponding models, since that would be unnecessary repetitive caching?
Is this idea good?

**Comment by Toricane** [comment]
I think I'm done now

**Comment by Toricane** [comment]
Yay merge conflicts
I'll resolve them when I'm on my computer

**Comment by Toricane** [comment]
Done!

**Comment by i0bs** [comment]
@Toricane This PR has merging conflicts. Additionally, we've updated `unstable` to implement a better CI workflow on `pre-commit`. Please run this when you pull and rebase.

**Comment by Toricane** [comment]
Okay, will do

**Comment by Toricane** [comment]
@goverfl0w merge conflicts are gone, fetched upstream, and `pre-commit` passed

**Comment by Toricane** [comment]
Fixed merge conflicts again

**Comment by Toricane** [comment]
Closing this, will make this more dynamic soon:tm:

**Pull request closed without merging**
