### PR TITLE
feat(guild)!: Converting `delete_message_days` in ban method to seconds

### PR DESCRIPTION
**Pull request by B1ue-Dev**
## About

This pull request is about changing the ban method (both as helper and _http method) from `delete_message_days` to `delete_message_seconds`, as mentioned in a recent docs change from Discord itself.
Do notice that this is a breaking change to the ban method.

## Checklist

- [x] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [x] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [x] For the documentation
  - [x] To add a new feature
  - [ ] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [x] A breaking change https://github.com/discord/discord-api-docs/pull/5219

### CODE REVIEW

**Comment by sillyElvy** [comment]
We can proceed with merging as this is a discord change, we don't need to hold this breaking change back

**Comment by B1ue-Dev** [comment]
> We can proceed with merging as this is a discord change, we don't need to hold this breaking change back

So you mean removing the breaking change line?

**Review by sillyElvy — APPROVED** [review]
Lgtm

**Comment by sillyElvy** [comment]
> > We can proceed with merging as this is a discord change, we don't need to hold this breaking change back
> 
> So you mean removing the breaking change line?

No it is still breaking, but usually changes would have to wait until v4.4. An exception to this are changes at the discord api which force us to adapt

**Comment by B1ue-Dev** [comment]
> > > We can proceed with merging as this is a discord change, we don't need to hold this breaking change back
> > 
> > So you mean removing the breaking change line?
> 
> No it is still breaking, but usually changes would have to wait until v4.4. An exception to this are changes at the discord api which force us to adapt

Ah, I see. Got that.

**Pull request merged**
