### PR TITLE
feat: add download helper method for Attachments

### PR DESCRIPTION
**Pull request by sillyElvy**
## About

This pull request adds a download method for attachments

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by Toricane** [comment]
Looks good, but pre commit failed, please run pre commit

**Comment by sillyElvy** [comment]
.pre-commit run

**Comment by sillyElvy** [comment]
> Looks good, but pre commit failed, please run pre commit

grafik

**Comment by Toricane** [comment]
Hmm ok

**Review by Toricane — APPROVED** [review]
LGTM!

**Pull request merged**
