### PR TITLE
fix!: prevent creating a payload for not present values in ComponentContext

### PR DESCRIPTION
**Pull request by sillyElvy**
## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [ ] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [x] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent): #483 
- [ ] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by sillyElvy** [comment]
Dang im dumb

give me a bit

**Comment by i0bs** [comment]
😬 i hate looking at context code, i'm passing this suffering over to Delta, still working on GW refact

**Comment by Jalancar** [comment]
Still getting an error when I don't pass an embed:

```
Traceback (most recent call last):
  File "venvs\discord_bot\lib\site-packages\interactions\api\http.py", line 258, in request
    async with self._session.request(
  File "venvs\discord_bot\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "venvs\discord_bot\lib\site-packages\aiohttp\client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "venvs\discord_bot\lib\site-packages\aiohttp\payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "C:\Program Files\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Embed is not JSON serializable

Task exception was never retrieved
future: <Task finished name='Task-34' coro=<_powermatch_button_callback() done, defined at discord_bot.py:2917> exception=TypeError('interactions.api.models.message.Message() argument after ** must be a mapping, not NoneType')>
Traceback (most recent call last):
  File "discord_bot.py", line 2928, in _powermatch_button_callback
    await ctx.edit(
  File "venvs\discord_bot\lib\site-packages\interactions\context.py", line 644, in edit
    await func()
  File "venvs\discord_bot\lib\site-packages\interactions\context.py", line 603, in func
    self.message = Message(**res, _client=self.client)
TypeError: interactions.api.models.message.Message() argument after ** must be a mapping, not NoneType
```

**Review by Jalancar — APPROVED** [review]
Looks good to me now

**Review by FayeDel — APPROVED** [review]
Finally tested this, LGTM :)
Will merge 👍🏻

**Pull request merged**
