### PR TITLE
feat: implement mention property

### PR DESCRIPTION
**Pull request by mAxYoLo01**
## About

This pull request is about the implementation of `mention` properties for the following classes: `User`, `Member`, `Role` and `Channel`.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [ ] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by mAxYoLo01** [comment]
The following code can output channel/member/roles with a given context, to try the feature:
```python
@bot.command(name="mention", description="Mention test", scope=server)
async def mention(ctx: interactions.CommandContext):
    channel: interactions.Channel = await ctx.get_channel()
    guild: interactions.Guild = await ctx.get_guild()
    roles = []
    for role_id in ctx.member.roles:
        role = await guild.get_role(role_id)
        roles.append(role.mention)
    await ctx.send(embeds=create_info_embed(
        f"Channel: {channel.mention}\nMember: {ctx.member.mention}\nRoles: {' '.join(roles)}"
    ))
```
And the output:
image

**Review by sillyElvy — APPROVED** [review]
LGTM 👍 

edit 2: nvm what i edited before I was just dumb lol

**Review by V3ntus — APPROVED** [review]
Looks good!

**Review by Toricane — APPROVED** [review]
LGTM too!

**Comment by sillyElvy** [comment]
quick question: did you run pre-commit? @mAxYoLo01

**Comment by FayeDel** [comment]
Hiya! This looks good to me too :)
I'll go ahead and merge this now, thank you for contributing!

**Pull request merged**
