### PR TITLE
feat:  Warn if people try to run d.py alongside interactions

### PR DESCRIPTION
**Pull request by silasary**
## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description
We frequently recieve support requests where provided code snippits start with the line "import discord" and inevitably don't work. 
Due to the nature of humans generally importing stuff alphabetically, we can do runtime check for this import, and yell at them.

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [ ] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [ ] I've updated / added  documentation, where applicable

### CODE REVIEW

**Comment by LordOfPolls** [comment]
Alternate idea. Move this check to client's sanity check method

**Comment by LordOfPolls** [comment]
Alternate idea. Move this check to client's sanity check method

**Comment by silasary** [comment]
Considered, implemented, then reverted upon further consideration 😂 

Take this thread as an example: https://discord.com/channels/789032594456576001/1110958056327626753/1110959282213621860

```py
import discord
from discord import app_commands
from discord.ext import commands
from interactions import slash_command, SlashContext, Permissions, slash_default_member_permission, Extension
...
bot = commands.Bot (command_prefix="*", intents = discord.Intents.all())
slash = slash_command(bot, sync_commands=True)
command_count = 0
staff = Permissions.MANAGE_ROLES

class Player(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @slash_command(name="X", description="X")
    @slash_default_member_permission(staff)
    async def hello(self, ctx: SlashContext):
        await ctx.send(f"Hey {ctx.author.mention}! Test")


bot.add_cog(Player(bot))

@bot.event
async def on_ready():
    print(f"Bot conectado como {bot.user.name}")
    await slash.sync_all_commands()

token = os.getenv('TOKEN')
bot.run(token)
```

They're using interactions decorators on a d.py client.  They're still going to run into issues, but they won't ever call sanity check.

**Comment by LordOfPolls** [comment]
Id argue that's extreme user error at that point. But fair point, then I have one more suggestion. Put it in the root init

**Comment by silasary** [comment]
That was my initial plan, but it felt weird.

**Comment by LordOfPolls** [comment]
It's standard practice for checks like this. Const feels weird, imo

**Comment by silasary** [comment]
Understandable.  I'll move it to init

**Comment by LordOfPolls** [comment]
oh fml. this targetted stable... dammit sil, i trusted you

**Comment by silasary** [comment]
Ooops. I blame the fact that stable and unstable were at the same place when I made the PR.

**Pull request merged**
