### PR TITLE
fix: minor ext bugs

### PR DESCRIPTION
**Pull request by Catalyst4222**
## About

This pr does two things relating to .ext:
- fixes the IndentationError in base.pyi, which makes it unable to be formatted by black
- Changes the MD5Hash typehint to point towards an existing class in hashlib

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by Catalyst4222** [comment]
I think something may be broken with pre-commit
image

**Review by sillyElvy — APPROVED** [review]

**Comment by sillyElvy** [comment]
> I think something may be broken with pre-commit

why?

**Comment by Catalyst4222** [comment]
It passed on my machine, but the automated checks here failed

**Comment by sillyElvy** [comment]
> It passed on my machine, but the automated checks here failed

Thats not your fault: 
grafik

**Comment by i0bs** [comment]
I'll get to fixing this when possible. People should not be using ext stuff and unstable right now.

**Pull request closed without merging**
