### PR TITLE
feat: Implement barebones AutoMod support.

### PR DESCRIPTION
**Pull request by FayeDel**
## About

This PR title essentially explains itself.
AutoMod support are currently in testing, so this is left as a draft PR until its live/widespread/more features are discovered.

This correlates to an earlier PR: #630 

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [X] I've made this pull request for/as: (check all that apply)
  - [X] Documentation
  - [X] Breaking change
  - [X] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by FayeDel** [comment]
Marking this as ready to review as AutoMod is now live according to discord docs :)

**Comment by sillyElvy** [comment]
> Marking this as ready to review as AutoMod is now live according to discord docs :)

Alright I'm making helpers later :heheahboi:

**Comment by sillyElvy** [comment]
Also you gotta merge conflict

**Comment by sillyElvy** [comment]
> Also you gotta merge conflict 

Got a*, Damn it autocorrect

**Review by sillyElvy — APPROVED** [review]
Lgtm I think

**Pull request merged**
