### PR TITLE
docs: Fix missing pages and duplicate type referencing.

### PR DESCRIPTION
**Pull request by FayeDel**
## About

This pull request fixes the missing reported `get()` related page and adds in the emoji section, alongside multiple type duplication references (see #documentation in the server).
It also updates locale accordingly in preparation for the next version release.

(This also serves as a test for fixing up-to-date docs on the main URL)

## Checklist

- [X] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [X] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [X] For the documentation
  - [ ] To add a new feature
  - [X] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

### CODE REVIEW

**Comment by Damego** [comment]
We also don't have page for `emoji.py`. Can you add it?

**Comment by sillyElvy** [comment]
(we wanted docs branch, no?)

**Comment by FayeDel** [comment]
Yes and no;
It would typically fit in the docs branch except that a good chunk of users lately need to use the get function for various reasons (there's a decent amount in the support forum posts) so I think it deserves priority before updating to the next version (as its easier to view when there are no helpers available to describe the get function for users)

**Comment by sillyElvy** [comment]
> Yes and no; It would typically fit in the docs branch except that a good chunk of users lately need to use the get function for various reasons (there's a decent amount in the support forum posts) so I think it deserves priority before updating to the next version (as its easier to view when there are no helpers available to describe the get function for users)

hm I see, but this would also make branch fuckup (somewhen) probably. So maybe it's best to maybe just delete the docs branch and make docs PRs directly onto stable so they're immediately available?

Also we can technically merge docs -> stable directly after this pr is merged.

but idk

**Comment by FayeDel** [comment]
-> for branch reasons rebase/merge commits are fine, as far as I can tell unstable is no different than documentation (based on the changes)
   -> unstable'll be merged to stable anyway so documentation branch to some degree would already be up to date
-> I don't.. know about deleting the docs branch? Its fine with or without it so I'd have to give it some thought ^^

**Comment by sillyElvy** [comment]
Well its mainly about if merging docs changes directly into stable is fine or not

**Comment by FayeDel** [comment]
That'd.. I guess depends on what docs changes it'd be related to

**Review by sillyElvy — APPROVED** [review]

**Pull request merged**
