### PR TITLE
feat: add permissions attr to Member

### PR DESCRIPTION
**Pull request by AstreaTSS**
## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description
Quick PR to add in `permissions` to `Member`, as that's given in interaction objects and can be useful.

## Changes
- Add `permissions` to `Member`.

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

### CODE REVIEW

**Comment by LordOfPolls** [comment]
The shouldnt be in the member object as this is instance-specific, not guild specific. Imo the context object should intercept and store this data, that way its ephemeral just like this data is

**Comment by AstreaTSS** [comment]
...how then? Do note that this is given for member objects in options too.

**Comment by LordOfPolls** [comment]
I said? The context object

**Comment by AstreaTSS** [comment]
Do you... want a mapping? Like `ctx.permissions[member]`? That doesn't sound that great for UX, those I suppose that could simplify channel permissions too.

**Comment by LordOfPolls** [comment]
I have an idea. Give me 24 hours to draft something

**Comment by i0bs** [comment]
Do we statically dispatch events, or are events aware of changes while being processed? If it's static – a mapping would work well, we'd just need to be considerate of indexing bounds

**Comment by AstreaTSS** [comment]
Closing this PR early as regardless of what happens, this likely isn't the way this feature will be implemented.

**Pull request closed without merging**
