### PR TITLE
fix: Update installation instructions for jurigged and sentry

### PR DESCRIPTION
**Pull request by TheLovinator1**
Use `discord-py-interactions` instead of just `interactions` so users can copy the text without it failing

## Pull Request Type

- [ ] Feature addition
- [x] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description

Use `discord-py-interactions` instead of just `interactions` so users can copy the text without it failing.

Old:
```
poetry add interactions[jurigged]                                                                                                                                                        
Could not find a matching version of package interactions
```
New:
```
poetry add discord-py-interactions[jurigged]
Using version ^5.6.0 for discord-py-interactions
Updating dependencies
Resolving dependencies...                               
...
```

## Changes

* interactions -> discord-py-interactions

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [ ] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [ ] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [ ] I've updated / added  documentation, where applicable

### CODE REVIEW

**Comment by TheLovinator1** [comment]
Oops, I force-pushed to my own repo and forgot that it changes it here, may have fucked up the pull request?

I also accidentally made a pull request with the wrong branch, I give up :(

**Comment by Damego** [comment]
`discord-py-interactions` is a previous name of this library, so we shouldn't use it.
However, in the instruction there is wrong package name. It should be `interactions.py`.

**Comment by Damego** [comment]
Also wrong target branch

**Comment by TheLovinator1** [comment]
>discord-py-interactions is a previous name of this library, so we shouldn't use it.

Both the README and the docs uses discord-py-interactions, should that be changed?

>Also wrong target branch

I changed the branch after the pull request and these commits got added so I changed back: image

**Comment by AstreaTSS** [comment]
`discord-py-interactions` is still a valid name - it's just an alternative to `interactions.py`. Using both is fine.

**Comment by LordOfPolls** [comment]
Merged manually because github was going to do some fuckery because of the branch base

**Pull request closed without merging**
