### PR TITLE
feat: add `thread_name` field in the webhook field

### PR DESCRIPTION
**Pull request by retr0-init**
## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description

This enables the API to create thread in forum and media channels.

## Changes

- Added `thread_name` field to the `api.http.http_requests.webhook.WebhookRequests.execute_webhook` method.
- Added `thread_name` field to the `models.discord.webhook.Webhook.send` method
- add exclusive check between the `thread_name` and `thread`

## Related Issues

#1721 

## Test Scenarios

```python
@interactions.slash_command(
    "test1", description="test channel command", scopes=[DEV_GUILD] if DEV_GUILD else None
)
@interactions.slash_option(
    name="channel",
    description="Channel",
    opt_type=interactions.OptionType.CHANNEL,
    required=True
)
async def test_cmd(self, ctx: interactions.SlashContext, channel: interactions.GuildForum):
    """Register as an extension command"""
    await ctx.send(f"Test Create a post in channel {channel.mention} with webhook")
    wbs: list[interactions.Webhook] = await channel.fetch_webhooks()
    if len(wbs) > 0:
        msg: interactions.Message = await wbs[0].send("test content", embed=interactions.Embed(
            title="Embed title",
            description="Embed desc"
        ), wait=True, thread_name="Post Title")
        await ctx.send(f"Created {msg.jump_url}")
```

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [x] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

### CODE REVIEW

**Comment by retr0-init** [comment]
Should I add a check in the method to say `thread and thread_name cannot be set together`? I think an exception should be created somewhere. Probably in the `send` method. 
Additionally, there should be a channel check whether this should be used there so another exception needs to be created.
I suggest two exception names: `WebhookConflictParameters` and `WebhookInvalidDestination`, which both inherits from `LibraryException`.
What names would you suggest?

**Comment by AstreaTSS** [comment]
Typically, input errors like this are just handled through `ValueError`. I don't see a need of adding a new type of error.

**Comment by retr0-init** [comment]
I think the error report from the discord API for channel checking is enough along with the warnings in the docstring. It should be ready for review.

**Review by silasary — APPROVED** [review]

**Comment by retr0-init** [comment]
I think this is good to be merged. Is there any further modification needed?

**Comment by silasary** [comment]
Yeah, I'm happy with it

**Pull request merged**
