### PR TITLE
refactor: optmize the project structure

### PR DESCRIPTION
**Pull request by sillyElvy**
## About

This PR improves the project structure and makes it more logical by moving the `attrs_utils` from `api/models` to a top-level `utils` directory. This is done because `attrs_utils` is used across the whole library and logically is better placed at the top of the library rather than in two subdirectories.

Additionally `get` and `utils` have been moved to this directory since they are not really methods of the client.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to ensure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by sillyElvy** [comment]
draft until imports

**Comment by sillyElvy** [comment]
works

**Review by Catalyst4222 — CHANGES_REQUESTED** [review]
`missing.pyi` doesn't need to exist, but other than that, it looks good

**Comment by Catalyst4222** [comment]
Merge conflicts, please fix

**Comment by sillyElvy** [comment]
> Merge conflicts, please fix

Done

**Comment by sillyElvy** [comment]
> > Merge conflicts, please fix
> 
> Done

Wait i fucked up

**Comment by sillyElvy** [comment]
> > > Merge conflicts, please fix
> > 
> > Done
> 
> Wait i fucked up 

Now

**Review by Catalyst4222 — APPROVED** [review]

**Pull request merged**
