### PR TITLE
feat!: make the library use `__all__` to not alias every import from another library

### PR DESCRIPTION
**Pull request by sillyElvy**
## About

https://ptb.discord.com/channels/789032594456576001/876490879815254097/981242475500941392 

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [x] Breaking change
  - [x] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by Toricane** [comment]
Should there be `__all__` in `interactions/__init__.py`?
This PR didn't add it there

**Comment by AstreaTSS** [comment]
> Should there be `__all__` in `interactions/__init__.py`? This PR didn't add it there

Not strictly necessary, it's fine if it's not specified there. It would be a pain to go through every file and determine every class to expose anyways, since this has all of them, and the `__all__`s in the other files will take care of that.

**Review by AstreaTSS — COMMENTED** [review]
Many of these `__all__`s could be tuples instead of lists. It's a slight performance boost that can add up.

**Comment by sillyElvy** [comment]
pre-commit.ci autofix

**Review by Toricane — APPROVED** [review]
LGTM!

**Pull request merged**
