### PR TITLE
feat: error handling for KeyboardInterrupt in `start()`

### PR DESCRIPTION
**Pull request by Toricane**
## About

This pull request introduces error handling for `KeyboardInterrupt` in `Client.start()`, which previously displayed a huge, useless traceback whenever someone stops the bot using `Ctrl + C`.

A side effect of this particular fix: any code that is *after* `client.start()` would be executed after `KeyboardInterrupt`, which is a cool feature in my opinion.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [ ] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Review by sillyElvy — CHANGES_REQUESTED** [review]
I'd do this:
```py
with contextlib.suppress(KeyboardInterrupt):
	# the try/except thing (without KeyboardInterrupt) 

log.info("KeyboardInterrupt detected. Shutting down Bot.")
```

**Comment by Toricane** [comment]
I think it should stay as log.error not log.info since it is an error and it is significant since it lets the user know that the bot has stopped

**Comment by sillyElvy** [comment]
> I think it should stay as log.error not log.info since it is an error and it is significant since it lets the user know that the bot has stopped

I don't like error, I think warning is enough

**Comment by i0bs** [comment]
Error is semantically correct as it signifies a breaking call that impedes on the running service, which KeyboardInterrupt does here.

**Comment by sillyElvy** [comment]
> Error is semantically correct as it signifies a breaking call that impedes on the running service, which KeyboardInterrupt does here.

Alright

**Comment by Toricane** [comment]
> I'd do this:
> 
> ```python
> with contextlib.suppress(KeyboardInterrupt):
> 	# the try/except thing (without KeyboardInterrupt) 
> 
> log.info("KeyboardInterrupt detected. Shutting down Bot.")
> ```

```py
def start(self) -> None:
    """Starts the client session."""
    try:
        self._loop.run_until_complete(self._ready())
    except (CancelledError, Exception) as e:
        raise e from e
    except KeyboardInterrupt:
        log.error("KeyboardInterrupt detected, shutting down the bot.")
```
@EdVraz this is what it looks like though, I think to try/except would be better since there are multiple exceptions to be caught.

**Review by sillyElvy — APPROVED** [review]
It's alright ig lol

**Pull request merged**
