### PR TITLE
feat: add alt methods for multi-arg params for prefixed cmds

### PR DESCRIPTION
**Pull request by AstreaTSS**
## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description
This PR adds in alternative methods for "multi-argument parameters" for prefixed command. More specifically, it allows using `ConsumeRest[...]` over `*, arg` and `tuple[...]` over `*arg`. Some people may find this improvement better.

For hybrid command users, this finally allows making an argument a consume rest argument for the prefixed command variant. Variable argument support was not added because... well, slash commands don't do anything like variable arguments at all.

## Changes
...see the description for the most part. The documentation for prefixed commands were updated too to show the new methods for declaring these types of variables.

## Test Scenarios
```python
@prefixed_command()
async def test(ctx: PrefixedContext, args: tuple[str, ...]):
    await ctx.reply(f"{len(args)} arguments: {', '.join(args)}")
```

```python
@prefixed_command()
async def test(ctx: PrefixedContext, arg: ConsumeRest[str]):
    await ctx.reply(arg)
```

```python
@hybrid.hybrid_slash_command(name="info")
@interactions.slash_option(
    name="arg",
    description="The argument to send",
    opt_type=interactions.OptionType.STRING,
    required=True,
)
async def cmd(ctx: hybrid.HybridContext, arg: interactions.ConsumeRest[str]):
    await ctx.reply(arg)
```

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

### CODE REVIEW

**Comment by i0bs** [comment]
Interesting, are we using the ellipsis placeholder constant as a reference for consume marker?

**Comment by AstreaTSS** [comment]
No, the ellipses have zero effect on anything. It's the `tuple` that has an effect, the ellipses just make it proper typehinting.

**Comment by AstreaTSS** [comment]
Also, this new title is inaccurate. Support was *already* there, it's literally just adding alternative means to use it.

**Comment by i0bs** [comment]
Oh, i just now see that. My apologies. I'll take the L 😔

**Review by LordOfPolls — APPROVED** [review]

**Comment by LordOfPolls** [comment]
Req review from sil - she uses this part of the lib far more than me, and iirc she was asking about this a bit ago

**Pull request merged**
