### PR TITLE
ref!: set GuildMember as a subclass of Member

### PR DESCRIPTION
**Pull request by mAxYoLo01**
## About

This pull request ensures that in the future, `Member` & `GuildMember` have the same attributes & functions.
As of now, there were still inconsistencies between the two.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [x] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Review by sillyElvy — CHANGES_REQUESTED** [review]
Revert method removal, the overridden methods are needed (for now) but I will make a PR some day

Also it's not breaking

**Comment by mAxYoLo01** [comment]
> Revert method removal, the overridden methods are needed (for now) but I will make a PR some day

Could you  explain why? I'll revert for the moment.

> Also it's not breaking

For me it is, as `roles` passes from a list of str to int.

**Comment by sillyElvy** [comment]
> > Revert method removal, the overridden methods are needed (for now) but I will make a PR some day
> 
> Could you  explain why? I'll revert for the moment.
> 
> > Also it's not breaking
> 
> For me it is, as `roles` passes from a list of str to int.
> 
> 

Guild ID


Ok that's really fair

**Comment by Damego** [comment]
image

**Comment by sillyElvy** [comment]
And that has to be reverted

**Comment by mAxYoLo01** [comment]
Yeah my bad that's what happens when you play with 5 branches at the same time and decide to stage all files

**Comment by sillyElvy** [comment]
> Yeah my bad that's what happens when you play with 5 branches at the same time and decide to stage all files

Me who uses pycharm github integration: your problems are beyond my understanding

**Review by sillyElvy — APPROVED** [review]

**Pull request merged**
