### PR TITLE
5.11.0

### PR DESCRIPTION
**Pull request by LordOfPolls**

### CODE REVIEW

**Comment by LordOfPolls** [comment]
Mergability conflict fixed - this is stable and ready for merge

**Review by AstreaTSS — APPROVED** [review]
it is so funny being nearly half of the commits for this release

**Review by eightween — APPROVED** [review]
image

**Review by i0bs — APPROVED** [review]
are we putting all breaking changes on backburner for 6.x? when are we moving to working on it?

**Pull request merged**
