### PR TITLE
fix(autocomplete dispatch): ID -> name 

### PR DESCRIPTION
**Pull request by sillyElvy**
This allows multi-guild usage when 2 or more scopes are used on a command since the command will have a different ID but the same name in different guilds. Reported [here](https://canary.discord.com/channels/789032594456576001/1006824593731887214/1006838362772078743)

## About

This pull request is about (X), which does (Y).

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by Damego** [comment]
In this case if i trigger autocomplete in first guild both funtions with different command ids will be called

image
image

**Comment by sillyElvy** [comment]
> In this case if i trigger autocomplete in first guild both funtions with different command ids will be called
> 
> image
> image
>  

You want to have different responses for different guilds with the same command?

**Comment by Damego** [comment]
> You want to have different responses for different guilds with the same command?

Yes! /s
I think it should call only command with equal command id

**Comment by sillyElvy** [comment]
> > You want to have different responses for different guilds with the same command?
> 
> Yes! /s
> I think it should call only command with equal command id

Is there a real need for that?

**Comment by Damego** [comment]
> Is there a real need for that?
Honestly idk. Just found this.

**Comment by sillyElvy** [comment]
> > Is there a real need for that?
> Honestly idk. Just found this.

I think we should just keep it as it is rn

**Review by Damego — APPROVED** [review]
So it works fine for me (tested in 2 guilds)

**Comment by Toricane** [comment]
It does make sense that the command with equivalent ID invokes only the autocomplete for it since the ID was given
I can imagine some sort of tag system or something where the command names are the same but autocomplete differently in different guilds
Would it be difficult to implement it? If it is, then I think it's fine

**Comment by sillyElvy** [comment]
> It does make sense that the command with equivalent ID invokes only the autocomplete for it since the ID was given
> I can imagine some sort of tag system or something where the command names are the same but autocomplete differently in different guilds
> Would it be difficult to implement it? If it is, then I think it's fine

Yeah it's kinda hard to do it/it requires effort which is not really nessecary, especially considering the fact that you can just check `ctx.guild_id` inside autocomplete i think?

**Comment by Toricane** [comment]
Ok, makes sense

**Review by Toricane — CHANGES_REQUESTED** [review]
Please resolve merge conflict

**Review by Toricane — APPROVED** [review]
LGTM!

**Pull request merged**
