### PR TITLE
Return embed on update

### PR DESCRIPTION
**Pull request by Morgandri1**
## About

This PR adds lets all embed methods return the embed object, allowing you to ctx.send in the same line as creating the embed

## Checklist

- [✅] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [✅] I've ensured the change(s) work on `3.8.6` and higher.
- [✅] I have added the `versionadded`, `versionchanged` and `deprecated` to any new or changed user-facing function I committed.

### Pull-Request specification

I've made this pull request: (check all that apply)
  - [ ] For the documentation
  - [ ] To add a new feature
  - [*] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

### CODE REVIEW

**Comment by Morgandri1** [comment]
Commit #5 (sorry theres so many) fixed the update comments

**Comment by Damego** [comment]
Don't worry about it. We can squash all your commits in one

**Review by Toricane — DISMISSED** [review]
LGTM!

**Review by Damego — CHANGES_REQUESTED** [review]
Change branch target

**Comment by Morgandri1** [comment]
changed branch to unstable

**Review by Toricane — APPROVED** [review]
LGTM!

**Review by Damego — APPROVED** [review]

**Pull request merged**
