### PR TITLE
chore!: release 4.2.0 

### PR DESCRIPTION
**Pull request by FayeDel**
## About

This PR lines up all of the commits on `unstable` and moving to `stable` to effectively lead us up to the changes we need to bring for version 4.2.0

There's multiple breaking changes from the RC candidate of 4.1.1 which lead to the decision to effectively bump the expected version as per semantic versioning.

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [X] I've made this pull request for/as: (check all that apply)
  - [X] Documentation
  - [X] Breaking change
  - [X] New feature/enhancement
  - [X] Bugfix

### CODE REVIEW

**Comment by AstreaTSS** [comment]
I should note that we are absolutely *not* following semantic versioning to the letter right now - we *kinda* already broke it many times 😅.

But it was decided that it was significant enough for a higher version bump anywho.

**Review by i0bs — APPROVED** [review]
Great job Delta. I look forward to your first ever release. :)

**Review by sillyElvy — APPROVED** [review]
I'd like to see this file deletion gone from the pr if possible but that's not required

**Comment by i0bs** [comment]
> I'd like to see this file deletion gone from the pr if possible but that's not required

what was it exactly? github didn't pick up on any file comments

**Comment by sillyElvy** [comment]
> > I'd like to see this file deletion gone from the pr if possible but that's not required
> 
> what was it exactly? github didn't pick up on any file comments

The deletion of the duplicated `bot.py`, it's in the pr but it was deleted from stable already

**Pull request merged**
