### PR TITLE
refactor: remove `Client.__resolve_events` and associated events

### PR DESCRIPTION
**Pull request by Catalyst4222**
## About

This pull request is removes `Client.__resolve_events` and associated events, since they do nothing

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Comment by sillyElvy** [comment]
Pre commit fails

**Comment by Catalyst4222** [comment]
> Pre commit fails

Works on my machine /shrug
Even running black (which failed) on the file manually, nothing changes

**Comment by sillyElvy** [comment]
> > Pre commit fails
> 
> Works on my machine /shrug
> Even running black (which failed) on the file manually, nothing changes

Try updating your unstable branch and merge it into your current

**Comment by Catalyst4222** [comment]
> Try updating your unstable branch and merge it into your current

`Current branch unregister-events is up to date.`

**Comment by sillyElvy** [comment]
> > Try updating your unstable branch and merge it into your current
> 
> `Current branch unregister-events is up to date.`

Tf

**Review by sillyElvy — APPROVED** [review]

**Pull request merged**
